 
//Heuristical Weights and Threshold
#define WEIGHT_VC_CLASS 100
#define WEIGHT_VC_TITLE 100
#define WEIGHT_VC_COUNT_GUIS 100
#define WEIGHT_E_CLASS 10
#define WEIGHT_E_EQUAL 1
#define WEIGHT_E_TITLE 1
#define WEIGHT_E_ENABALED 1
#define WEIGHT_E_HIDDEN 1
#define WEIGHT_E_IMAGE 1
#define WEIGHT_E_VALUE 1
#define WEIGHT_E_TARGET 1
#define WEIGHT_E_ACTION 1
#define INTER_ACTION_LONG_DELAY 1.0
#define INTER_ACTION_SHORT_DELAY 1.0

#define VALUE_ONE_PARAMETER 1
#define VALUE_ZERO_PARAMETER 0

//Action Flags
#define START_AUTO_CLICKED @"START_AUTO_CLICKED"
#define NEXT_ACTION_CLICKED @"NEXT_ACTION_CLICKED"
#define BACK_BUTTON_CLICKED @"BACK_BUTTON_CLICKED"
#define NO_ACTION_CLICKED @"NO_ACTION_CLICKED"
#define FLIP_VIEW_CLICKED @"FLIP_VIEW_CLICKED"

